project_id = "ufgbavxidpmikiwicifv"

[functions.detect-country]
verify_jwt = false

[functions.send-doctor-email]
verify_jwt = false

[functions.license-renewal-reminder]
verify_jwt = false

[functions.paystack-payment]
verify_jwt = false

[functions.summarize-consultation]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false
