// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufgbavxidpmikiwicifv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZ2JhdnhpZHBtaWtpd2ljaWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNzkzNTYsImV4cCI6MjA4Nzc1NTM1Nn0.Q207kuJPPx0AReztT3hkR6_RBpnk03Xi5IGqGqpheWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});